config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ideas do
    resources :votes, only: :create
  end

  resources :votes, only: [:update, :destroy]

  post '/chatrooms/:chatroom_id/messages', to: 'messages#create', as: :chatroom_messages

  get '/dashboard', to: 'ideas#dashboard'
  patch '/approve/:id', to: "ideas#approve", as: :approve
  patch '/decline/:id', to: "ideas#decline", as: :decline
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_one_attached :photo

  validates :title, presence: true
  validates :problem, presence: true
  validates :solution, presence: true
  validates :address, presence: true
  # validate :allow_vote

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  scope :most_popular, -> { left_joins(:votes).group(:id).order("COUNT(votes.id) DESC").limit(5) }

  scope :by_votes, -> (direction) { left_joins(:votes).group(:id).order("COUNT(votes.id) #{direction.upcase}") }

  scope :by_status, -> (status) { where(status: status) }

  def pre_vote_find(current_user)
    self.votes.find { |vote| vote.user_id == current_user.id }
  end

  def set_status
    if (self.votes.count >= self.goal) && (self.municipality == true)
      self.status = "Pending"
    end
    self.save
  end

  # def allow_vote
  #   if self.votes.count > self.goal
  #     errors.add(:votes, "The limit is reached")
  #   end
  # end

  def has_feedback?
    votes_with_comment = votes.where.not(comment: nil)
    votes_with_comment.length > 0
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ideas
  has_many :votes
  has_many :voted_ideas, through: :votes, class_name: 'Idea', foreign_key: :idea_id, source: :idea
  # validates :role, inclusion: { in: %w(Resident Municipality) }
  has_one_attached :photo

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :idea
  belongs_to :user

  # with this validation the vote is unique for every user
  validates :user, uniqueness: { scope: :idea }

  after_create :check_idea_status

  def check_idea_status
    self.idea.set_status
  end
  # validate :allow_vote

  # def allow_vote
  #   if idea.votes.count > idea.goal
  #     errors.add(:votes, "The limit is reached")
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :photo, :role])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :email, :photo])
  end

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_idea, only: [:show, :edit, :update, :destroy, :approve, :decline]
  before_action :set_label, only: [:show, :approve, :decline]

  def dashboard
    @ideas = Idea.all
    @idea = Idea.new

      if params[:status].present?
        @ideas = @ideas.by_status(params[:status])
      end
      if params[:votes].present?
        @ideas = @ideas.by_votes(params[:votes])
      end


    @latest_ideas = Idea.order(:created_at).limit(5)
    @popular_ideas = Idea.most_popular

    # @popular_ideas = Idea.includes(:votes).order("votes DESC")
    @my_ideas = current_user.ideas.order(created_at: :desc)
    @my_voted_ideas = current_user.voted_ideas

    @chatroom = Chatroom.first
    @message = Message.new

  end

  def index
    if user_signed_in?
      @ideas = Idea.geocoded.near(current_user.address, 5, units: :km)
    else
        if params[:query].present?
          @ideas = Idea.geocoded.near(params[:query], 5, units: :km)
        else
          @ideas = Idea.all.geocoded
        end
    end

    @markers = @ideas.map do |idea|
      {
        lat: idea.latitude,
        lng: idea.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { idea: idea })
      }
    end

  end

  def show

   end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user
    if @idea.save
      redirect_to idea_path(@idea)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @idea.update(idea_params)
    redirect_to idea_path(@idea)
  end

  def destroy
    @idea.destroy
    redirect_to ideas_path
  end

  def approve
    @idea.status = "Approved"
    @idea.save
    respond_to do |format|
      format.js
    end
  end

  def decline
    @idea.status = "Declined"
    @idea.save
    respond_to do |format|
      format.js
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :problem, :solution, :address, :photo, :goal)
  end

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def set_label
    if @idea.status == "Approved"
      @label = "bg-success text-light status-label"
     elsif @idea.status == "Declined"
      @label = "bg-danger text-light status-label"
     else
      @label = "bg-light text-dark status-label"
     end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
    else
        render "chatrooms/show"
    end
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @idea = Idea.find(params[:idea_id])
    @idea.votes.create(user_id: current_user.id)
    @vote = @idea.pre_vote_find(current_user)
    @vote.save
    respond_to do |format|
      format.js
      format.html { redirect_to idea_path(@idea, anchor: "vote-#{@vote.id}")
    }
    # @idea.set_status
  end
end

def update
  @vote = Vote.find(params[:id])
  @idea = @vote.idea
  @vote.update(vote_params)
  redirect_to idea_path(@vote.idea)
end

def destroy
  @vote = Vote.find(params[:id])
  @vote.destroy
  # redirect_to idea_path(@vote.idea)
  redirect_to idea_path(@vote.idea)
end

private

def vote_params
  params.require(:vote).permit(:comment)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end

    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end

    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # little twist to make it work equally with an asset or a url
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end

app/views/chatrooms/_chat.html.erb
<h2>#Municipality InfoChat</h2>
<p>Most important information will be published here:</p>
    <% if current_user.role == "municipality" %>
     <%= simple_form_for [chatroom, message ], remote: true do |f| %>
        <%= f.label :content, "Publish here:"%>
        <%= f.input :content, as: :string, label: false, placeholder: "Message" %>
        <% end %>
    <% end %>

<div id="messages" data-chatroom-id="<%= chatroom.id %>">
    <% chatroom.messages.reverse.each do |message| %>
    <%= render(partial: "messages/message", locals: { message: message }) %>
    <% end %>
</div>

app/views/ideas/_congrats.html.erb
          <% if current_user.role != "municipality" %>
            <% if idea.votes.count >= idea.goal %>
              <div class="show-congratulations">


                <% if idea.user == current_user %>
                  <div class="congrats">
                    <p>Congratulations!</p>
                  </div>
                  <p class="m-0">Your idea has reached its goal.</p>
                  <% if idea.municipality == true %>
                    <p class="m-0">Wait for your local municipality to contact you soon.</p>
                  <% else %>
                    <p class="m-0">Reach out to the participants and make it come true!</p>
                  <% end %>

                <% else %>

                  <div class="congrats">
                    <p>Congratulations!</p>
                  </div>
                  <p class="m-0">The idea has reached its goal.</p>
                  <% if idea.municipality == true %>
                    <p class="m-0">Your local municipality will decide on it soon.</p>
                  <% else %>
                    <p class="m-0">The participants are on their way to making it come true!</p>
                  <% end %>

                <% end %>


              </div>
            <% end %>
          <% end %>

app/views/ideas/_info_window.html.erb
<div class="mapboxgl-popup-content">
  <% if idea.photo.attached?  %>
    <%= cl_image_tag idea.photo.key, crop: :fill, class: "show-img" %>
  <% end %>
  <h6 class="mt-2"><strong><%= idea.title %></strong></h6>
  <p><%= idea.address %></p>
  <% if idea.votes.count == 1 %>
    <p><%= idea.votes.count %> vote</p> 
  <% else %>
    <p class="mb-0" style="color: #797979;"><%= idea.votes.count %> votes</p>
  <% end %>
</div>

app/views/ideas/_new-idea.html.erb
        <h2>Pitch your idea</h2>
        <p class="pb-3">Shape your opinion and pitch your idea!</p>
            <%= simple_form_for idea, id: "new-idea-form" do |f| %>
            <%= f.input :title %>
            <%= f.input :problem %>
            <%= f.input :solution %>
            <%= f.label :address, "Address * (Please include the postcode)"%>
            <%= f.input :address, as: :string, label: false %>
            <%= f.input :photo, as: :file %>

            <%= f.label :municipality, "Does your idea require involvment of your local municipality?
            By selecting 'Yes' your idea will take place only with the approval of your town hall. By deselecting 'Yes' your idea will take place once the number of total partecipants is achieved. Every partecipant will collaborate at the realization of the idea." %>
                <div class="d-flex align-items-start pl-3">
                <%= f.input :municipality, as: :boolean, label: false, input_html: {id: "municipality-needed"} %>
                <p>Yes</p>
                </div>

                <div id="participators-field" class="participators-hide">
                    <%= f.label :goal, "How many people do you need to participate in your idea? *" %>
                    <%= f.input :goal, label: false %>
                </div>
                <div class="d-flex justify-content-center">
                    <%= button_tag type: 'submit', class: "btn btn-warning py-2 mt-3" do %>
                    <i class="far fa-plus-square pr-1"></i> Add Idea
                    <% end %>
                </div>
            <% end %>

app/views/ideas/approve.js.erb
$('#approvedModalCenter').modal('show')

document.querySelector("#label-idea").innerHTML = '<%= @idea.status %>'

document.querySelector("#label-idea").className = "";
document.querySelector("#label-idea").classList.add('bg-success', 'text-light', 'status-label');

app/views/ideas/decline.js.erb
$('#declineModalCenter').modal('show')

document.querySelector("#label-idea").innerHTML = '<%= @idea.status %>'

document.querySelector("#label-idea").className = "";
document.querySelector("#label-idea").classList.add('bg-danger', 'text-light', 'status-label');     

app/views/ideas/deny.js.erb
$('#declineModalCenter').modal('show')

document.querySelector("#label-idea").innerHTML = '<%= @idea.status %>'

document.querySelector("#label-idea").className = "";
document.querySelector("#label-idea").classList.add('bg-danger', 'text-light', 'status-label');

app/views/ideas/edit.html.erb
<div class="container d-flex edit-idea py-5">
    <div class="w-50">
        <h1>Change your idea</h1>
        <p class="subtitle">Enhance the potential of your idea and change it here!</p>
        <%= simple_form_for @idea do |f| %>
        <%= f.input :title %>
        <%= f.input :problem %>
        <%= f.input :solution %>

        <%= f.input :address %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class: 'btn btn-warning py-2' %>
        <% end %>
    </div>
    <%= image_tag "edit-idea.svg" %>
</div>

app/views/ideas/index.html.erb
<div class="m-4 pt-5">
  <div class="d-flex">
    <div class=" box-card-index mr-3">
      <h2>Explore initiatives around you</h2>
      <p>
        These are all the ideas from people living in your neighborhood.
        <br> Your vote can make the real difference!
      </p>
      <% @ideas.each do |idea| %>
        <%= link_to idea_path(idea), class: 'card-link' do %>
          <div class="card py-4 px-4 d-flex index-card">

            <div class="icon-index">
              <% if idea.municipality == true %>
                <i class="fas fa-landmark"></i>
              <% else %>
                <i class="fas fa-handshake"></i>
              <% end %>
            </div>

            <div class='user-index'>
              <% if idea.user.photo.attached?  %>
                <%= cl_image_tag idea.user.photo.key, crop: :fill, class: 'avatar m-0 p-0' %>
              <% else %>
                <p class="letter avatar"><%= idea.user.first_name.first.capitalize %><%= idea.user.last_name.first.capitalize %></p>
              <% end %>
              <div class='user-name ml-2'>
                <p><strong class="p-0 m-0"><%= idea.user.first_name %></strong></p>
              <small class='date'><%= time_ago_in_words(idea.created_at) %> ago</small>
              </div>
            </div>

            <div class='title-index mt-3'>
              <h4><%= idea.title %></h4>
            </div>

            <div class='content-index'>
              <p><%= truncate(idea.problem, length: 120) %></p>
            </div>

            <div class='footer-index'>
              <% if idea.votes.count == 1 %>
                <%= idea.votes.count %> vote
              <% else %>
                <%= idea.votes.count %> votes
              <% end %>
            </div>

          </div>
        <% end %>
      <% end %>

      </div>
        <div class='w-100 map'>
          <div id="map"
          style="width: 100%; height: 800px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          class="mapboxgl-popup mapboxgl-popup-content">
        </div>
      </div>
    </div>
  </div>
</div>



<%# GOOD HTML STRUCTURE USING BOOTSTRAP GRID %>
<%# <div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card">

      # CONTENT

      </div>
    </div>
  </div>
</div> %>

app/views/ideas/show.html.erb
<div class="container container-show py-5">
  <div class="row card-show">

    <%# IMAGE %>
    <div class="col-sm-12 p-0">
     <% if @idea.photo.attached?  %>
       <%= cl_image_tag @idea.photo.key, crop: :fill, class: "show-img" %>
     <% end %>
    </div>

    <%# LEFT SIDE %>
    <div class="col-sm-12 col-md-8">

      <div class="show-user d-flex align-items-center justify-content-between">
         <div class='user-index'>
              <% if @idea.user.photo.attached?  %>
                <%= cl_image_tag @idea.user.photo.key, crop: :fill, class: 'avatar m-0 p-0' %>
              <% else %>
                <p class="letter avatar"><%= @idea.user.first_name.first.capitalize %><%= @idea.user.last_name.first.capitalize %></p>
              <% end %>
              <div class='user-name ml-2'>
                <p><strong class="p-0 m-0"><%= @idea.user.first_name %></strong></p>
              <small class='date'><%= time_ago_in_words(@idea.created_at) %> ago</small>
              </div>
        </div>

        <div class="show-icons">

          <% if @idea.user == current_user %>
          <%= link_to edit_idea_path(@idea), class: "pr-2" do %>
          <i class="fas fa-edit"></i>
          <% end %>
          <% end %>

          <% if @idea.user == current_user || current_user.role == "municipality" %>
          <%= link_to idea_path(@idea), method: :delete, data: {confirm: 'Are you sure?'} do %>
          <i class="fas fa-trash"></i>
          <% end %>
          <% end %>

          <% if @idea.user != current_user && current_user.role != "municipality" %>
          <%= link_to (@idea), class: "pr-2" do %>
          <i class="fas fa-flag"></i>
          <% end %>
          <% end %>

        </div>
      </div>

      <div class="show-details">

        <div class="show-title">
          <div class="d-flex justify-content-between align-items-center">
             <h1><%= @idea.title %></h1>

              <div class="d-flex  align-items-center">
                <div class="mr-3">
                  <%# if the idea reached the goal will have the label showing: %>
                  <% if @idea.votes.count >= @idea.goal %>
                      <small class="<%= @label %>" id="label-idea"><%= @idea.status %></small>
                  <% end %>
                </div>
                <div class="icon-show">
                  <% if @idea.municipality == true %>
                    <i class="fas fa-landmark"></i>
                  <% else %>
                    <i class="fas fa-handshake"></i>
                  <% end %>
                </div>
              </div>

          </div>
        </div>


        <p class="details-light"><i class="fas fa-map-marker-alt"></i> <%= @idea.address %></p>

        <div class="details-description">
          <p class="tag">PROBLEM</p>
          <p><%= @idea.problem %></p>
        </div>
        <div class="details-description">
          <p class="tag">SOLUTION</p>
          <p><%= @idea.solution %></p>
        </div>


      <%# FEEDBACK %>
      <% if @idea.has_feedback? %>
        <div class="details-description">
          <% if current_user.role == "municipality" || @idea.user == current_user  %>
          <p class="tag">FEEDBACK</p>
            <% @idea.votes.each do |vote|  %>
              <% unless vote.comment == nil %>
              <div class="details-description pt-0 mt-0">
                <div class="user-feedback"><small> <%= time_ago_in_words(vote.updated_at) %> ago</small></div>
                <p><%= vote.comment %></p>
              </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>

    <%# RIGHT SIDE %>
    <div class="col-sm-12 col-md-4 text-center">
     <%# if the user is municipality %>
      <% if current_user.role == "municipality" %>
        <div class="pt-5 d-flex justify-content-center">
            <%# if the idea has the right vote can be approved/declined %>

            <% if @idea.municipality == true %>
              <% if @idea.votes.count >= @idea.goal %>
                <div class="approved-declined">
                    <p class="subtitle"> The idea will be:</p>
                      <div>
                        <%= link_to "Approved", approve_path(@idea), method: :patch, remote: true, class: "btn btn-outline-success" %>
                        <%= link_to "Declined", decline_path(@idea), method: :patch, remote: true, class: "btn btn-outline-danger show-declined-button" %>
                      </div>
                </div>
              <% else %>
                <div class="approved-declined-waiting">
                  <div>
                    <p class="mb-0">The idea still has to reach its goal to be approved or declined.</p>
                  </div>
                </div>
              <% end %>
            <% end %>

        </div>
      <% else %>
        <% unless @idea.user == current_user %>

          <%# VOTE & PARTICIPATE BUTTONS %>

          <div id='vote-btn' class="show-vote d-flex justify-content-center align-items-center">
            <% pre_vote =  @idea.pre_vote_find(current_user) %>
            <% if pre_vote %>
              <%= button_to vote_path(pre_vote), method: :delete, remote: true, class: "btn btn-warning py-2 w-100 vote-btn" do %>

                <% if @idea.municipality == true %>
                  <i class="far fa-square mr-1"></i></i> Unvote
                <% else %>
                  <i class="fas fa-handshake-slash mr-1"></i> Resign
                <% end %>

              <% end %>
            <% else %>
              <%= button_to idea_votes_path(@idea), method: :post, remote: true, class: "btn btn-warning py-2 w-100 vote-btn" do %>

                <% if @idea.municipality == true %>
                  <i class="far fa-check-square mr-1"></i> Vote
                <% else %>
                  <i class="fas fa-handshake mr-1"></i> Participate
                <% end %>

              <% end %>
            <% end %>
          </div>

        <% end %>
        <% end %>


        <%# PROGRESS BAR %>
        <div class="show-progress d-flex justify-content-center">
          <div class="progress-container" data-total="<%= @idea.goal %>" data-vote="<%= @idea.votes.count %>">

          </div>
        </div>

        <%# CONGRATULATIONS %>
        <div class="d-flex justify-content-center" id="congratulations">
        <%= render partial: 'congrats', locals: { idea: @idea } %>
        </div>


        <div class="d-flex justify-content-center">
          <div class="show-goal-info">

            <p><i class="fas fa-bullseye mr-2"></i>Goal: <strong><%= @idea.goal %></strong>

              <% if @idea.municipality == true %>
                votes
              <% else %>
                participants
              <% end %>

            </p>

            <% if @idea.municipality == true %>
              <p class="mb-0"><i class="far fa-check-square mr-2"></i>Status: <strong><%= @idea.votes.count %></strong>

                <% if @idea.votes.count == 0 %>
                  vote
                <% else %>
                  votes
                <% end %>

              </p>
            <% else %>
              <p class="mb-0"><i class="fas fa-handshake mr-1"></i>Status: <strong><%= @idea.votes.count %></strong>
                <% if @idea.votes.count == 0 %>
                  participant
                <% else %>
                  participants
                <% end %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!--Approve Modal -->
<div class="modal fade" id="approvedModalCenter" tabindex="-1" role="dialog" aria-labelledby="approvedModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <button type="button" class="close text-right pr-3 pt-2" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <div class="modal-body-approved">
        <div class="pl-4"><h5 class="text-success">The idea has been successfully approved!</h5>
          <p class="pb-3">Set the date for the appointment with the resident who proposed it.</p>
          <div class="d-flex justify-content-center mb-4">
          <a href = "mailto:<%= @idea.user.email %>" class="btn btn-warning py-2">Send Email</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--Decline Modal -->
<div class="modal fade" id="declineModalCenter" tabindex="-1" role="dialog" aria-labelledby="declineModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <button type="button" class="close text-right pr-3 pt-2" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <div class="modal-body-approved">
        <div class="pl-4"><h5 class="text-danger">The idea has been officially declined.</h5>
          <p class="pb-3">The resident who proposed it will be informed shortly.</p>
        </div>

      </div>
    </div>
  </div>
</div>

<!--Feedback Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <button type="button" class="close text-right pr-3 pt-2" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="message-container card py-3 my-3 px-3" id="message-<%= message.id %>">
  <i class="author">
    <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
  </i>
  <p><%= message.content %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-custom navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <h2 class="logo">Votify</h2>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
    <i class="fas fa-bars" style="color:#fff; font-size:23px;"></i>
    </span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.role == "municipality" %>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
            <div class="ml-1">
              <% if current_user.photo.attached?  %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: 'avatar' %>
              <% else %>
              <p class="letter avatar">
                <%= current_user.first_name.first.capitalize %><%= current_user.last_name.first.capitalize %></p>
              <% end %>
            </div>
          <% else %>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "View ideas", ideas_path, class: "nav-link" %>
          </li>
          <%= link_to "Pitch your idea", new_idea_path, class: "nav-link" %>
          <li>
            <div class="ml-1">
              <% if current_user.photo.attached?  %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: 'avatar' %>
              <% else %>
              <p class="letter avatar">
                <%= current_user.first_name.first.capitalize %><%= current_user.last_name.first.capitalize %></p>
              <% end %>
            </div>
          </li>
        <% end %>

      <% else %>
      <li class="nav-item">
        <%= link_to "How it works", root_path(anchor: 'how-it-works'), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Testimonials", root_path(anchor: 'testimonials'), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "View ideas", ideas_path, class: "nav-link" %>
      </li>
      </li>
      <%= link_to "Pitch your idea", new_idea_path, class: "nav-link" %>
      <li>
      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/votes/create.js.erb
$('#exampleModal').modal('show')

document.getElementById('vote-btn').innerHTML = '<%= button_to vote_path(@vote), method: :delete, remote: true, class: "btn btn-warning py-2 w-100 vote-btn" do %> <% if @idea.municipality == true %> <i class="far fa-square mr-1"></i></i> Unvote <% else %> <i class="fas fa-handshake-slash mr-1"></i> Resign <% end %> <% end %>'

document.querySelector('.modal-body').innerHTML = '<%= j render "form", vote: @vote %>'

document.querySelector('#congratulations').innerHTML = '<%= j render "ideas/congrats", idea: @idea %>'